name: Format Files
run-name: Format files using Biome
on:
  push:
    branches:
      - main
permissions:
  contents: write
  statuses: write
  actions: write
jobs:
  prettier-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup github-actions[bot] git config
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Format files
        run: npm run format
      - name: Check for changes
        id: changes
        run: |
          git add -A
          if git diff --staged --quiet; then
            echo "changes_exist=false" >> "$GITHUB_OUTPUT"
          else
            echo "changes_exist=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Output if changes exist
        env:
          CHANGES_EXIST: ${{ steps.changes.outputs.changes_exist }}
        run: echo "$CHANGES_EXIST"
      - name: Commit formatting changes, if any
        if: steps.changes.outputs.changes_exist == 'true'
        run: |
          git commit -m "chore: commit file formatting changes via GitHub Actions"
          git push
